version: '3.4'

services:

    productdb:
        container_name: productdb
        environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin1234 
          - POSTGRES_DB=ProductDb
        restart: always
        ports:
          - "5435:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data/
    basketdb:
        container_name: basketdb
        restart: always
        ports:
          - "5437:5438"
    pgadmin:
        container_name: pgadmin
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
          - PGADMIN_DEFAULT_PASSWORD=admin1234
        restart: always
        ports:
          - "5070:80"
        volumes:
          - pgadmin_data:/root/.pgadmin
    products.api:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
      ports:
         - "10000:8080"
      depends_on:
       - productdb

    basket.api:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
      ports:
         - "10001:8080"

